[build]
  command = "pip install -r requirements.txt"
  functions = "infra/netlify/functions"
  publish = "public"

[build.environment]
  PYTHONPATH = "src"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
